language: ruby
rvm:
  - 2.1.1
  - 2.0.0
script: bundle exec rake
env:
  global: AUCHANDIRECT_TEST_PASSWORD=123secret
matrix:
  include:
    - rvm: 2.1.1
      env: AUCHANDIRECT_TEST_EMAIL=auchandirect.scrapi.211@mailinator.com
    - rvm: 2.O.0
      env: AUCHANDIRECT_TEST_EMAIL=auchandirect.scrapi.200@mailinator.com